---
version: '3.5'
services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-aragon}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ajar24332}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - '5432:5432'
    networks:
      - postgres
    restart: always
networks:
  postgres:
    driver: bridge
volumes:
  postgres:
